version: "3"

services:
  app:
    build:
      context: whoami/.
    ports:
      - "8000:8000"
    volumes:
      - ./whoami:/app
    environment:
      - DB_HOST=db
      - DB_NAME=whoami
      - DB_USER=yogi
      - DB_PASS=yogi9644
      - DEBUG=1
      - S3_STORAGE_BACKEND=0
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=whoami
      - POSTGRES_USER=yogi
      - POSTGRES_PASSWORD=yogi9644
