version: '3.7'

services:
  terraform:
    image: hashicorp/terraform:0.12.21
    volumes:
      - .:/infra
    working_dir: /infra
    environment:
      - AWS_ACCESS_KEY_ID=<access key>
      - AWS_SECRET_ACCESS_KEY=<secret key>
      - AWS_SESSION_TOKEN=<token>
